spring.datasource.url=jdbc:mysql://localhost:3306/medical_system
spring.datasource.username=root
spring.datasource.password=Sasan@1212

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false